#!/bin/bash

set -e
# Automatically added by dh_installmenu/13.6ubuntu1
if [ -x "`command -v update-menus`" ]; then update-menus ; fi
# End automatically added section

if [ "$1" = "remove" ]; then
  sed -i '/^nameserver/d' /etc/resolvconf/resolv.conf.d/head
  resolvconf -u
  systemctl disable --now resolvconf.service
  nmcli networking off
  nmcli networking on
fi

exit 0
