#!/bin/bash

systemctl enable --now resolvconf.service

cleanbrowsing1="nameserver 185.228.168.168"
cleanbrowsing2="nameserver 185.228.169.168"
LIST="${cleanbrowsing1}$'\n'${cleanbrowsing2}"
sed -i '/^nameserver/d' /etc/resolvconf/resolv.conf.d/head
echo $LIST >> /etc/resolvconf/resolv.conf.d/head
resolvconf -u
nmcli networking off
nmcli networking on

exit 0
