#!/bin/bash
set -e
# Automatically added by dh_installmenu/13.6ubuntu1
if [ "$1" = "configure" ] && [ -x "`command -v update-menus`" ]; then
  update-menus
fi
# End automatically added section

if [ "$1" = "install" ]; then
  systemctl enable --now resolvconf.service

  DEFAULTS="nameserver 185.228.168.168
nameserver 185.228.169.168"

  sed -i '/^nameserver/d' /etc/resolvconf/resolv.conf.d/head
  echo "$DEFAULTS" | tee -a /etc/resolvconf/resolv.conf.d/head

  resolvconf -u
  nmcli networking off
  nmcli networking on
fi

exit 0
