#!/bin/bash

systemctl enable --now resolvconf.service

DEFAULTS="nameserver 185.228.168.168
nameserver 185.228.169.168"

sed -i '/^nameserver/d' /etc/resolvconf/resolv.conf.d/head
echo "$DEFAULTS" | tee -a /etc/resolvconf/resolv.conf.d/head

resolvconf -u
nmcli networking off
nmcli networking on

exit 0
