#!/bin/bash
set -e
# Automatically added by dh_installmenu/13.6ubuntu1
if [ "$1" = "configure" ] && [ -x "`command -v update-menus`" ]; then
  update-menus
fi
# End automatically added section

DNS=$(resolvectl status | grep "Current DNS Server:" | awk '{print $4}')
if [[ $DNS == "185.228.168.168"* ]] || [[ $DNS == "185.228.169.168"* ]] ||
[[ $DNS == "208.67.222.123"* ]] || [[ $DNS == "208.67.220.123"* ]] ||
[[ $DNS == "1.1.1.3"* ]] || [[ $DNS == "1.0.0.3"* ]] ||
[[ $DNS == "94.140.14.15"* ]] || [[ $DNS == "94.140.15.16"* ]]; then
  echo "DNS Minder Already Enabled"
else
  systemctl enable --now resolvconf.service

  DEFAULTS="nameserver 185.228.168.168
nameserver 185.228.169.168"

  sed -i '/^nameserver/d' /etc/resolvconf/resolv.conf.d/head
  echo "$DEFAULTS" | tee -a /etc/resolvconf/resolv.conf.d/head

  resolvconf -u
  nmcli networking off
  nmcli networking on
fi

exit 0
